### PR TITLE
Add client roles

### PR DESCRIPTION
**Pull request by seanly**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by kassiope9l** [comment]
@mrmateo waiting for merge this pr...

**Comment by mrmateo** [comment]
Apologies, I missed this. I'm taking a look right now.

**Comment by mrmateo** [comment]
Un-did import changes to keep this PR focused on the actual code changes (and to continue current formatting of not using wildcard imports).

**Comment by mrmateo** [comment]
Thanks @seanly for the PR and @kassiope9l  for the tag :) 

I have one other change I would like to add in this next version and then will do a release of this plugin.

**Pull request merged**
